spring:
  application:
    name: restaurant-web
  profiles:
    active:
      - restaurant
      - db
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SYSTEM
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database: oracle
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
