restaurant:
  name: bar mleczny
  units:
    - kg
    - tbsp
    - glass
    - u
  ingredientType:
    - name: ONION
      vegan: true
    - name: PEPPER
      vegan: true
    - name: SALAD
      vegan: true
    - name: CORN
      vegan: true
    - name: CHICKEN
      vegan: false
    - name: BEEF
      vegan: false
    - name: PORK
      vegan: false
    - name: FISH
      vegan: false
    - name: LAMB
      vegan: false
  stockCapacity:
    ONION:
      amount: 40
      unit: "kg"
    PEPPER:
      amount: 40
      unit: "kg"
    SALAD:
      amount: 40
      unit: "kg"
    CORN:
      amount: 40
      unit: "kg"
    CHICKEN:
      amount: 40
      unit: "kg"
    BEEF:
      amount: 40
      unit: "kg"
    PORK:
      amount: 40
      unit: "kg"
    FISH:
      amount: 40
      unit: "kg"
    LAMB:
      amount: 40
      unit: "kg"
  kitchenWare:
    - fryingPan
    - knife
    - choppingBoard
    - spatula
    - bowl
    - wok
  recipes:
    - name: "Fried chicken with sliced vegetables"
      neededIngredients:
        ONION:
          amount: 2
          unit: "u"
        PEPPER:
          amount: 3
          unit: "u"
      neededKitchenWare:
        - "fryingPan"
        - "knife"
        - "choppingBoard"
      instructions:
        "1": "Chop vegetables"
        "2": "Chop chicken"
        "3": "Fry chopped chicken"
        "4": "Add vegetables to frying chicken"

    - name: "Vegetable Stir Fry"
      neededIngredients:
        SALAD:
          amount: 2
          unit: "u"
        CORN:
          amount: 1
          unit: "u"
      neededKitchenWare:
        - "wok"
        - "spatula"
      instructions:
        "1": "Chop salad"
        "2": "Cook corn"
        "3": "Stir fry vegetables"
        "4": "Serve with rice"
  chiefs:
    - name: "John Lennon"
      chiefLevel: "MASTER"
      knownRecipes:
        - "Fried chicken with sliced vegetables"
        - "Vegetable Stir Fry"
    - name: "Jan Kowalski"
      chiefLevel: "BEGINNER"
      knownRecipes:
        - "Vegetable Stir Fry"